FROM python:3.11.5-bookworm

WORKDIR /app

RUN apt update && apt install -y \
    opus-tools \
    ffmpeg && \
    rm -rf /var/lib/apt/lists/*


RUN pip3 install --no-cache-dir poetry

COPY entrypoint.sh /app

